title: Vignesh Selvaraj
logo: /asserts/photo1682251583.jpeg
description: Software Engineer | Python Backend Developer | Python, Flask, Django, DRF, FastAPI | PostgreSQL, MySQL, MongoDB, Redis, SQLite| CI/CD | AWS | Celery, RabbitMQ | NumPy, Pandas, Matplotlib | Ensuring Quality & Efficiency 🚀
show_downloads: true
theme: jekyll-theme-minimal